//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork22
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganizationsEntities : DbContext
    {
        public OrganizationsEntities()
            : base("name=OrganizationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Publications> Publications { get; set; }
        public virtual DbSet<SubscriptionTable> SubscriptionTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }

        private static OrganizationsEntities context;
        public static OrganizationsEntities GetContext()
        {
            if (context == null) context = new OrganizationsEntities();
            return context;
        }
    }
}
