//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork22
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class View_1
    {
        public System.DateTime SubscriptionDate { get; set; }
        public int Months { get; set; }
        public double Discount { get; set; }
        public string PublName { get; set; }
        public string OrgName { get; set; }
        public int Pages { get; set; }
        public string Photo { get; set; }
        public string PhotoFull
        {
            get
            {
                string namePhoto;
                if (this.Photo == null) return namePhoto = Directory.GetCurrentDirectory() + "\\img\\" + "unknown.png";
                else
                {
                    namePhoto = Directory.GetCurrentDirectory() + "\\img\\" + Photo;
                }
                return namePhoto;
            }
        }
    }
}
